local drift = require("pr.drift")

describe("drift.compute_drift + commit_to_buffer + buffer_to_commit", function()
	describe("identity (no changes)", function()
		it("returns commit_line unchanged for identical files", function()
			local d = drift.compute_drift({ "a", "b", "c" }, { "a", "b", "c" })
			assert.equals(1, drift.commit_to_buffer(d, 1))
			assert.equals(2, drift.commit_to_buffer(d, 2))
			assert.equals(3, drift.commit_to_buffer(d, 3))
		end)

		it("returns buffer_line unchanged for identical files", function()
			local d = drift.compute_drift({ "a", "b", "c" }, { "a", "b", "c" })
			assert.equals(1, drift.buffer_to_commit(d, 1))
			assert.equals(2, drift.buffer_to_commit(d, 2))
			assert.equals(3, drift.buffer_to_commit(d, 3))
		end)

		it("handles single-line identical files", function()
			local d = drift.compute_drift({ "a" }, { "a" })
			assert.equals(1, drift.commit_to_buffer(d, 1))
			assert.equals(1, drift.buffer_to_commit(d, 1))
		end)
	end)

	describe("pure insertion", function()
		it("shifts all commit lines down for insertion at top", function()
			local d = drift.compute_drift({ "a", "b", "c" }, { "x", "y", "a", "b", "c" })
			assert.equals(3, drift.commit_to_buffer(d, 1))
			assert.equals(4, drift.commit_to_buffer(d, 2))
			assert.equals(5, drift.commit_to_buffer(d, 3))
		end)

		it("returns nil from buffer for newly-inserted top lines", function()
			local d = drift.compute_drift({ "a", "b", "c" }, { "x", "y", "a", "b", "c" })
			assert.is_nil(drift.buffer_to_commit(d, 1))
			assert.is_nil(drift.buffer_to_commit(d, 2))
			assert.equals(1, drift.buffer_to_commit(d, 3))
			assert.equals(2, drift.buffer_to_commit(d, 4))
			assert.equals(3, drift.buffer_to_commit(d, 5))
		end)

		it("leaves commit lines unchanged for insertion at bottom", function()
			local d = drift.compute_drift({ "a", "b", "c" }, { "a", "b", "c", "x", "y" })
			assert.equals(1, drift.commit_to_buffer(d, 1))
			assert.equals(2, drift.commit_to_buffer(d, 2))
			assert.equals(3, drift.commit_to_buffer(d, 3))
		end)

		it("returns nil from buffer for newly-inserted bottom lines", function()
			local d = drift.compute_drift({ "a", "b", "c" }, { "a", "b", "c", "x", "y" })
			assert.is_nil(drift.buffer_to_commit(d, 4))
			assert.is_nil(drift.buffer_to_commit(d, 5))
		end)

		it("shifts lines after a middle insertion", function()
			local d = drift.compute_drift({ "a", "b", "c", "d" }, { "a", "b", "x", "y", "c", "d" })
			assert.equals(1, drift.commit_to_buffer(d, 1))
			assert.equals(2, drift.commit_to_buffer(d, 2))
			assert.equals(5, drift.commit_to_buffer(d, 3))
			assert.equals(6, drift.commit_to_buffer(d, 4))
		end)

		it("returns nil from buffer for inserted middle lines", function()
			local d = drift.compute_drift({ "a", "b", "c", "d" }, { "a", "b", "x", "y", "c", "d" })
			assert.is_nil(drift.buffer_to_commit(d, 3))
			assert.is_nil(drift.buffer_to_commit(d, 4))
		end)
	end)

	describe("pure deletion", function()
		it("returns nil for deleted top lines", function()
			local d = drift.compute_drift({ "a", "b", "c", "d" }, { "c", "d" })
			assert.is_nil(drift.commit_to_buffer(d, 1))
			assert.is_nil(drift.commit_to_buffer(d, 2))
			assert.equals(1, drift.commit_to_buffer(d, 3))
			assert.equals(2, drift.commit_to_buffer(d, 4))
		end)

		it("shifts buffer_to_commit for surviving lines after top deletion", function()
			local d = drift.compute_drift({ "a", "b", "c", "d" }, { "c", "d" })
			assert.equals(3, drift.buffer_to_commit(d, 1))
			assert.equals(4, drift.buffer_to_commit(d, 2))
		end)

		it("returns nil for deleted bottom lines", function()
			local d = drift.compute_drift({ "a", "b", "c", "d" }, { "a", "b" })
			assert.equals(1, drift.commit_to_buffer(d, 1))
			assert.equals(2, drift.commit_to_buffer(d, 2))
			assert.is_nil(drift.commit_to_buffer(d, 3))
			assert.is_nil(drift.commit_to_buffer(d, 4))
		end)

		it("returns nil for deleted middle lines", function()
			local d = drift.compute_drift({ "a", "b", "c", "d", "e" }, { "a", "b", "e" })
			assert.equals(1, drift.commit_to_buffer(d, 1))
			assert.equals(2, drift.commit_to_buffer(d, 2))
			assert.is_nil(drift.commit_to_buffer(d, 3))
			assert.is_nil(drift.commit_to_buffer(d, 4))
			assert.equals(3, drift.commit_to_buffer(d, 5))
		end)
	end)

	describe("replacement", function()
		it("same-size: maps commit lines to buffer lines 1:1", function()
			local d = drift.compute_drift({ "a", "b", "c", "d" }, { "a", "X", "Y", "d" })
			assert.equals(1, drift.commit_to_buffer(d, 1))
			assert.equals(2, drift.commit_to_buffer(d, 2))
			assert.equals(3, drift.commit_to_buffer(d, 3))
			assert.equals(4, drift.commit_to_buffer(d, 4))
		end)

		it("grow: maps existing commit lines, surplus buffer lines are unmappable", function()
			local d = drift.compute_drift({ "a", "b", "c" }, { "a", "X", "Y", "Z", "c" })
			assert.equals(1, drift.commit_to_buffer(d, 1))
			assert.equals(2, drift.commit_to_buffer(d, 2))
			assert.equals(5, drift.commit_to_buffer(d, 3))
			assert.equals(1, drift.buffer_to_commit(d, 1))
			assert.equals(2, drift.buffer_to_commit(d, 2))
			assert.is_nil(drift.buffer_to_commit(d, 3))
			assert.is_nil(drift.buffer_to_commit(d, 4))
			assert.equals(3, drift.buffer_to_commit(d, 5))
		end)

		it("shrink: surplus commit lines return nil", function()
			local d = drift.compute_drift({ "a", "b", "c", "d", "e" }, { "a", "X", "e" })
			assert.equals(1, drift.commit_to_buffer(d, 1))
			assert.equals(2, drift.commit_to_buffer(d, 2))
			assert.is_nil(drift.commit_to_buffer(d, 3))
			assert.is_nil(drift.commit_to_buffer(d, 4))
			assert.equals(3, drift.commit_to_buffer(d, 5))
		end)
	end)

	describe("combined edits", function()
		it("handles a delete followed by an insertion", function()
			local d = drift.compute_drift({ "a", "b", "c", "d", "e" }, { "a", "c", "X", "d", "e" })
			assert.equals(1, drift.commit_to_buffer(d, 1))
			assert.is_nil(drift.commit_to_buffer(d, 2))
			assert.equals(2, drift.commit_to_buffer(d, 3))
			assert.equals(4, drift.commit_to_buffer(d, 4))
			assert.equals(5, drift.commit_to_buffer(d, 5))
		end)

		it("handles multiple non-adjacent hunks", function()
			local d = drift.compute_drift({ "a", "b", "c", "d", "e", "f" }, { "X", "a", "b", "c", "e", "Y", "f" })
			assert.equals(2, drift.commit_to_buffer(d, 1))
			assert.equals(3, drift.commit_to_buffer(d, 2))
			assert.equals(4, drift.commit_to_buffer(d, 3))
			assert.is_nil(drift.commit_to_buffer(d, 4))
			assert.equals(5, drift.commit_to_buffer(d, 5))
			assert.equals(7, drift.commit_to_buffer(d, 6))
		end)
	end)

	describe("edge cases", function()
		it("commit_line = 0 returns nil", function()
			local d = drift.compute_drift({ "a" }, { "a" })
			assert.is_nil(drift.commit_to_buffer(d, 0))
			assert.is_nil(drift.commit_to_buffer(d, -1))
		end)

		it("buffer_line = 0 returns nil", function()
			local d = drift.compute_drift({ "a" }, { "a" })
			assert.is_nil(drift.buffer_to_commit(d, 0))
			assert.is_nil(drift.buffer_to_commit(d, -1))
		end)

		it("non-number input returns nil", function()
			local d = drift.compute_drift({ "a" }, { "a" })
			assert.is_nil(drift.commit_to_buffer(d, "1"))
			assert.is_nil(drift.buffer_to_commit(d, nil))
		end)

		it("whole-file replacement: every commit line is nil except none-coincidental", function()
			local d = drift.compute_drift({ "a", "b", "c" }, { "x", "y", "z" })
			assert.equals(1, drift.commit_to_buffer(d, 1))
			assert.equals(2, drift.commit_to_buffer(d, 2))
			assert.equals(3, drift.commit_to_buffer(d, 3))
		end)

		it("empty committed, non-empty buffer: every buffer line is nil from buffer", function()
			local d = drift.compute_drift({}, { "x", "y" })
			assert.is_nil(drift.buffer_to_commit(d, 1))
			assert.is_nil(drift.buffer_to_commit(d, 2))
		end)

		it("non-empty committed, empty buffer: every commit line is nil from commit", function()
			local d = drift.compute_drift({ "a", "b" }, {})
			assert.is_nil(drift.commit_to_buffer(d, 1))
			assert.is_nil(drift.commit_to_buffer(d, 2))
		end)
	end)

	describe("round-trip", function()
		it("commit_to_buffer(buffer_to_commit(N)) == N for unchanged lines", function()
			local d = drift.compute_drift({ "a", "b", "c", "d", "e" }, { "a", "X", "Y", "d", "e" })
			-- Lines 1, 4, 5 are unchanged (a, d, e).
			for _, commit_line in ipairs({ 1, 4, 5 }) do
				local buf = drift.commit_to_buffer(d, commit_line)
				assert.is_not_nil(buf, "commit line " .. commit_line .. " should map to buffer")
				assert.equals(commit_line, drift.buffer_to_commit(d, buf), "round-trip mismatch for commit_line=" .. commit_line)
			end
		end)

		it("buffer_to_commit(commit_to_buffer(N)) == N for unchanged lines", function()
			local d = drift.compute_drift({ "a", "b", "c", "d", "e" }, { "a", "X", "Y", "d", "e" })
			-- Buffer lines 1, 4, 5 are unchanged.
			for _, buffer_line in ipairs({ 1, 4, 5 }) do
				local commit = drift.buffer_to_commit(d, buffer_line)
				assert.is_not_nil(commit, "buffer line " .. buffer_line .. " should map to commit")
				assert.equals(buffer_line, drift.commit_to_buffer(d, commit), "round-trip mismatch for buffer_line=" .. buffer_line)
			end
		end)

		it("identity round-trips for every line in unchanged files", function()
			local d = drift.compute_drift({ "a", "b", "c" }, { "a", "b", "c" })
			for n = 1, 3 do
				assert.equals(n, drift.commit_to_buffer(d, drift.buffer_to_commit(d, n)))
				assert.equals(n, drift.buffer_to_commit(d, drift.commit_to_buffer(d, n)))
			end
		end)
	end)
end)
