describe("filter.pr_list state", function()
	local filter
	before_each(function()
		package.loaded["pr.pickers.filter"] = nil
		filter = require("pr.pickers.filter")
	end)

	it("defaults to all", function()
		assert.equals("all", filter.state.pr_list_filter)
	end)

	it("cycles through filters in order", function()
		-- Start from a known position so the cycle order is deterministic.
		filter.set_pr_filter("mine")
		filter.cycle_pr_filter()
		assert.equals("assigned", filter.state.pr_list_filter)
		filter.cycle_pr_filter()
		assert.equals("review-requested", filter.state.pr_list_filter)
		filter.cycle_pr_filter()
		assert.equals("all", filter.state.pr_list_filter)
		filter.cycle_pr_filter()
		assert.equals("mine", filter.state.pr_list_filter)
	end)

	it("pr_list_label wraps the current filter", function()
		assert.equals("[all] ", filter.pr_list_label())
		filter.set_pr_filter("mine")
		assert.equals("[mine] ", filter.pr_list_label())
	end)

	it("reset returns pr_list_filter to all", function()
		filter.cycle_pr_filter()
		filter.cycle_pr_filter()
		filter.reset()
		assert.equals("all", filter.state.pr_list_filter)
	end)

	it("set_pr_filter accepts known values", function()
		filter.set_pr_filter("mine")
		assert.equals("mine", filter.state.pr_list_filter)
		filter.set_pr_filter("review-requested")
		assert.equals("review-requested", filter.state.pr_list_filter)
		filter.set_pr_filter("assigned")
		assert.equals("assigned", filter.state.pr_list_filter)
		filter.set_pr_filter("all")
		assert.equals("all", filter.state.pr_list_filter)
	end)

	it("set_pr_filter ignores unknown values", function()
		filter.set_pr_filter("mine")
		filter.set_pr_filter("garbage")
		assert.equals("mine", filter.state.pr_list_filter)
	end)

	it("exposes PR_FILTERS for command completion", function()
		assert.are.same({ "mine", "assigned", "review-requested", "all" }, filter.PR_FILTERS)
	end)
end)
