local gitlab = require("pr.providers.gitlab")

describe("gitlab._parse_global_id", function()
	it("extracts the trailing numeric id", function()
		assert.equals(12345, gitlab._parse_global_id("gid://gitlab/Note/12345"))
		assert.equals(1, gitlab._parse_global_id("gid://gitlab/AwardEmoji/1"))
	end)

	it("returns nil for non-numeric ids", function()
		assert.is_nil(gitlab._parse_global_id("gid://gitlab/Discussion/abc"))
	end)

	it("returns nil for non-string input", function()
		assert.is_nil(gitlab._parse_global_id(nil))
		assert.is_nil(gitlab._parse_global_id(42))
	end)
end)

describe("gitlab._parse_discussion_id", function()
	it("extracts the hex segment after Discussion/", function()
		assert.equals("abc123", gitlab._parse_discussion_id("gid://gitlab/Discussion/abc123"))
	end)

	it("falls back to the raw input when no Discussion/ marker", function()
		assert.equals("plain", gitlab._parse_discussion_id("plain"))
	end)

	it("returns nil for non-string input", function()
		assert.is_nil(gitlab._parse_discussion_id(nil))
		assert.is_nil(gitlab._parse_discussion_id(42))
	end)
end)

describe("gitlab._url_encode", function()
	it("encodes slashes as %2F", function()
		assert.equals("foo%2Fbar", gitlab._url_encode("foo/bar"))
	end)

	it("encodes spaces and quotes", function()
		assert.equals("a%20b", gitlab._url_encode("a b"))
		assert.equals("a%3Db", gitlab._url_encode("a=b"))
	end)

	it("leaves alphanumerics and unreserved chars untouched", function()
		assert.equals("Foo-Bar_baz.123~", gitlab._url_encode("Foo-Bar_baz.123~"))
	end)

	it("returns empty string for nil", function()
		assert.equals("", gitlab._url_encode(nil))
	end)
end)

describe("gitlab._parse_remote_url", function()
	it("parses SSH form with .git suffix", function()
		local owner, repo, path = gitlab._parse_remote_url("git@gitlab.com:group/project.git")
		assert.equals("group", owner)
		assert.equals("project", repo)
		assert.equals("group/project", path)
	end)

	it("parses SSH form without .git", function()
		local owner, repo, path = gitlab._parse_remote_url("git@gitlab.com:group/project")
		assert.equals("group", owner)
		assert.equals("project", repo)
		assert.equals("group/project", path)
	end)

	it("parses HTTPS form", function()
		local owner, repo, path = gitlab._parse_remote_url("https://gitlab.com/group/project.git")
		assert.equals("group", owner)
		assert.equals("project", repo)
		assert.equals("group/project", path)
	end)

	it("handles nested namespaces (subgroups)", function()
		local owner, repo, path = gitlab._parse_remote_url("git@gitlab.com:group/sub/project.git")
		assert.equals("group/sub", owner)
		assert.equals("project", repo)
		assert.equals("group/sub/project", path)
	end)

	it("trims trailing whitespace", function()
		local owner, repo, path = gitlab._parse_remote_url("git@gitlab.com:g/p.git\n")
		assert.equals("g", owner)
		assert.equals("p", repo)
		assert.equals("g/p", path)
	end)

	it("returns nils for unrecognised URLs", function()
		local owner, repo, path = gitlab._parse_remote_url("not-a-url")
		assert.is_nil(owner)
		assert.is_nil(repo)
		assert.is_nil(path)
	end)
end)

describe("gitlab reaction mappings", function()
	it("round-trips each canonical key in REACTION_TO_AWARD", function()
		for content, award in pairs(gitlab._REACTION_TO_AWARD) do
			assert.equals(content, gitlab._AWARD_TO_REACTION[award], "round-trip failed for " .. content .. " -> " .. award)
		end
	end)

	it("accepts both 'smile' and 'laughing' as LAUGH inbound", function()
		assert.equals("LAUGH", gitlab._AWARD_TO_REACTION["smile"])
		assert.equals("LAUGH", gitlab._AWARD_TO_REACTION["laughing"])
	end)

	it("outbound LAUGH is `smile` (matches GitHub's chosen glyph 😄)", function()
		assert.equals("smile", gitlab._REACTION_TO_AWARD["LAUGH"])
	end)

	it("covers GitLab extras", function()
		assert.equals("fire", gitlab._REACTION_TO_AWARD["FIRE"])
		assert.equals("partying_face", gitlab._REACTION_TO_AWARD["PARTY"])
		assert.equals("wave", gitlab._REACTION_TO_AWARD["WAVE"])
		assert.equals("clap", gitlab._REACTION_TO_AWARD["CLAP"])
	end)
end)
